# Supervisord running really should be a prerequisite for this, not encoded into it
---
- hosts: all
  roles:
    - role: "graphite"
    - role: "supervise"
      name: "carbon-cache"
      command: "{{ graphite_python }} carbon-cache.py --nodaemon start"
      chdir: "{{ graphite_install_dir }}/bin"
      app_env:
        PATH: "{{ graphite_bin }}"

    - role: "supervise"
      name: graphite-web
      command: "{{ graphite_gunicorn_django }} --bind={{graphite_web_bind}}"
      app_home: "{{graphite_install_dir}}/webapp/graphite"
      app_env:
        PATH: "{{ graphite_bin }}"
