# Supervisord running really should be a prerequisite for this, not encoded into it
---
- hosts: all
  vars:
    home: /home/vagrant
    virtualenv_home: "{{ home }}/.virtualenvs"
    graphite:
      packages:
        - graphite-web
        - carbon
      version: "master"
      carbon_conf_files:
        - carbon.conf
        - storage-schemas.conf

    system_packages:
      - libcairo2-dev
      - gunicorn
      - python-cairo
      - python-rrdtool
      - memcached

  pre_tasks:
    - name: system requirements
      apt: pkg={{ item }} state=latest
      sudo: yes
      with_items: system_packages

    - name: install graphite packages
      git: repo=https://github.com/graphite-project/{{ item }}
           version={{ graphite.version }}
           dest={{ home }}/{{ item }}
           depth=1

      with_items: graphite.packages

    - name: workaround for network blocking git://
      command: sed -i -e "s/git+git/git+https/" {{ home }}/{{ item }}/requirements.txt
      with_items: graphite.packages

    - name: install graphite deps
      pip: requirements={{ home }}/{{ item }}/requirements.txt
           virtualenv={{ virtualenv_home }}/graphite
      with_items: graphite.packages

    - name: setup graphite apps
      command: chdir=/home/vagrant/{{ item }}
               python setup.py build install
      sudo: yes
      with_items: graphite.packages

    - name: copy example confs to main conf
      command: chdir={{ home }}/carbon/conf
               creates={{ home }}/carbon/conf/{{ item }} 
               cp {{ item }}.example {{ item }}
      with_items: graphite.carbon_conf_files

  roles:
    - role: "supervise"
      name: carbon-cache
      command: carbon-cache.py --nodaemon
      chdir: "/home/vagrant/carbon/bin"
      app_env:
        PATH: "/home/vagrant/.virtualenv/graphite/bin"

    - role: "supervise"
      name: graphite-web
      command: gunicorn django webapp/graphite
      app_home: "/home/vagrant/graphite-web"
      app_env:
        PATH: "/home/vagrant/.virtualenv/graphite/bin"
