---
- hosts: all
  vars:
    home: /home/vagrant
    virtualenv_home: ${home}/.virtualenv
    graphite:
      packages:
        - graphite-web
        - carbon
      version: "0.9.12"

    pip_packages:
      - supervisor

    system_packages:
      - libcairo2-dev
      - gunicorn
      - python-cairo
      - memcached


  tasks:
    - name: system requirements
      apt: pkg=${item} state=latest
      sudo: yes
      with_items: ${system_packages}

    - name: pip install packages
      pip: name=${item} virtualenv=${virtualenv_home}/${item}
      with_items: ${pip_packages}

    - name: supervisor config
      copy: src=supervisor/supervisord.conf dest=${home}

    - name: supervisor.d dir
      file: dest=${home}/supervisor.d state=directory

    - name: is supervisor running?
      command: test -f ${home}/supervisord.pid
      ignore_errors: True
      register: supervisor_check

    - name: "start supervisor if it isn't already running"
      command: chdir=${home} .virtualenv/supervisor/bin/supervisord
      when: supervisor_check.rc != 0

    - name: install graphite packages
      git: repo=https://github.com/graphite-project/${item} version=${graphite.version} dest=${home}/${item} depth=1
      with_items: ${graphite.packages}

    - name: workaround for network blocking git://
      command: sed -i -e "s/git+git/git+https/" ${home}/${item}/requirements.txt
      with_items: ${graphite.packages}

    - name: install graphite deps
      pip: requirements=${home}/${item}/requirements.txt state=latest virtualenv=${virtualenv_home}/graphite
      with_items: ${graphite.packages}

    - name: copy graphite conf
      copy: src=graphite/graphite.conf dest=${home}/supervisor.d/

    - name: start up graphite in supervisor
      command: chdir=${home} .virtualenv/supervisor/bin/supervisorctl reread graphite:*

    - command: chdir=${home} .virtualenv/supervisor/bin/supervisorctl restart graphite:*
